name: google_doc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router:
  # Network & Auth
  dio: ^5.9.0
  dio_smart_retry: ^6.0.0
  google_sign_in: ^6.2.1
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  
  # Real-time
  socket_io_client: ^2.0.3+1
  
  # Editor
  flutter_quill: ^11.5.0
  flutter_quill_extensions:
  # Data & Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # Storage (Use Hive or Secure Storage instead of SharedPreferences for tokens)
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3               # Add for offline storage
  hive_flutter: ^1.1.0       # Add for offline storage
  connectivity_plus: ^5.0.2  # Add for network detection
  
  # Utils
  uuid: ^4.5.1
  collection: ^1.18.0
  crypto: ^3.0.3 
  shimmer:
  flutter_slidable:
  share_plus:

  flutter_svg:
  cached_network_image:
  flutter_portal:
  animations: ^2.1.1
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0


flutter:
  uses-material-design: true